### ISSUE TITLE
TimeTable is not generating

### ISSUE THREAD

**Issue by RohanKrishna500** [huzaifabhutta/TimetableGeneratorApp#2]
i added all the courses,professor,everything but when i generate it shows me error like this
![image](https://github.com/mHuzefa/TimetableGeneratorApp/assets/144703643/1409fc68-a56f-4145-8886-93c694eb6579)

**Comment by huzaifabhutta** [comment]
Hi @RohanKrishna500, I am not currently maintaining the repository but it seems like an old package throwing error.
